# Generated by Django 2.0.5 on 2018-05-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phishr_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('company_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='company_id',
            field=models.CharField(max_length=100),
        ),
    ]
