# Generated by Django 2.0.5 on 2018-05-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0003_auto_20180524_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_test_1',
            name='description',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='operation_test_2',
            name='description',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='operation_test_3',
            name='description',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='operation_test_4',
            name='description',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='operation_test_5',
            name='description',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='operation_test_6',
            name='description',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
