# Generated by Django 2.0.5 on 2018-05-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0005_auto_20180530_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ass_master',
        ),
    ]
