# Generated by Django 2.0.5 on 2018-05-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0006_delete_ass_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('company_id', models.CharField(max_length=100)),
                ('clicked_link', models.BooleanField(default=False)),
            ],
        ),
    ]
