# Generated by Django 2.0.5 on 2018-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0009_companyco_trial_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation_test_1',
            name='clicked_link',
        ),
        migrations.AddField(
            model_name='companyco_trial_campaign',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='new_campaign',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='operation_test_1',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='operation_test_2',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='operation_test_3',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='operation_test_4',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='operation_test_5',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='operation_test_6',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
    ]
