# Generated by Django 2.0.5 on 2018-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0010_auto_20180531_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_test_1',
            name='clicked_link',
            field=models.BooleanField(default=False),
        ),
    ]
