# Generated by Django 2.0.5 on 2018-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0013_campoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campoon',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='companyco_trial_campaign',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='new_campaign',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='operation_test_1',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='operation_test_2',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='operation_test_3',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='operation_test_4',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='operation_test_5',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='operation_test_6',
            name='employee_id',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
    ]
