# Generated by Django 2.0.5 on 2018-06-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0015_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tEST',
            new_name='Test_Icles',
        ),
    ]
