# Generated by Django 2.0.5 on 2018-06-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0017_new_shit_nigga'),
    ]

    operations = [
        migrations.CreateModel(
            name='KIKE_ME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('company_id', models.CharField(max_length=100)),
                ('clicked_link', models.BooleanField(default=False)),
                ('employee_id', models.CharField(default='DEFAULT', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='phishr_user',
            name='trial_user',
            field=models.BooleanField(default=False),
        ),
    ]
