# Generated by Django 2.0.5 on 2018-06-22 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0021_poop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='poop',
        ),
    ]
