# Generated by Django 2.0.5 on 2018-07-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phishr', '0026_passwordrecovery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishr_user',
            old_name='trial_user',
            new_name='paid',
        ),
    ]
